### ISSUE TITLE
How to support u3d web player

### ISSUE THREAD

**Issue by gclsoft** [mw-felker/WebServicesForUnity3D#1]
The webservice http://127.0.0.1:10081/crossdomain.xml returns 
"<?xml version='1.0'?><cross-domain-policy><allow-access-from domain=* to-ports=* \/><\/cross-domain-policy>"
How to get rid of the double quotes "".
U3d gets error:

UriFormatException: Invalid URI: Invalid port number
MonoForks.System.Uri.Parse (UriKind kind, System.String uriString)
MonoForks.System.Uri.ParseUri (UriKind kind)
MonoForks.System.Uri.Parse ()
MonoForks.System.Uri..ctor (System.String uriString, Boolean dontEscape)
MonoForks.System.Uri..ctor (System.String uriString)
(wrapper remoting-invoke-with-check) MonoForks.System.Uri:.ctor (string)
MonoForks.System.Windows.Interop.PluginHost.get_SourceUri ()
MonoForks.System.Windows.Browser.Net.CrossDomainPolicyManager.GetCachedWebPolicy (MonoForks.System.Uri uri)
UnityEngine.UnityCrossDomainHelper.GetSecurityPolicy (System.String requesturi_string, IPolicyProvider policyProvider)
UnityEngine.UnityCrossDomainHelper.GetSecurityPolicy (System.String requesturi_string)

**Comment by maxfelker** [comment]
Hey @gclsoft sorry for the late reply - I don't know how this shakes out now since it's been almost 5 years. I am going to close this for now.
